services:
  plausible_db:
    volumes:
      - ./backup/postgres:/backup
      - ./logs/postgres:/var/log/postgresql

  plausible_events_db:
    volumes:
      - ./clickhouse/local-backup.xml:/etc/clickhouse-server/config.d/local-backup.xml:ro
      - ./backup/clickhouse:/backup

  plausible:
    ports:
      - 80:80
      - 443:443

  crontab:
    build: ./crontab
    restart: always
    volumes:
      - ./backup:/backup/
      - ./crontab/aws:/root/.aws
      - ./logs:/logs
      - ./crontab/last_bks:/last_bks
      - ./crontab/locks:/locks
    depends_on:
      plausible_db:
        condition: service_healthy
      plausible_events_db:
        condition: service_healthy
    secrets:
      - plausible-conf

volumes:
  db-data:
    driver: local
  event-data:
    driver: local

secrets:
  plausible-conf:
    file: ./.env