version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backup/postgres:/backup
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
      - ./clickhouse/local-backup.xml:/etc/clickhouse-server/config.d/local-backup.xml:ro
      - ./backup/clickhouse:/backup

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0.0-rc.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./reverse-proxy/nginx/plausible:/etc/nginx/nginx.conf
      # - ./reverse-proxy/nginx/conf.d:/etc/nginx/conf.d:ro
      # - ./reverse-proxy/nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - 8080:80
      - 44443:443
    depends_on:
      - plausible
  
  crontab:
    build: ./crontab
    restart: always
    volumes:
      - ./backup:/backup
      - ./reverse-proxy/nginx/:/etc/nginx/nginx.conf
    depends_on:
      - nginx

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local
