version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backup/postgres:/backup
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:22.6-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
      - ./clickhouse/local-backup.xml:/etc/clickhouse-server/config.d/local-backup.xml:ro
      - ./backup/clickhouse:/backup

    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:v2.0.0
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx-reverse-proxy:/etc/nginx/
      - ./crontab/letsencrypt/conf:/etc/letsencrypt
      - ./crontab/letsencrypt/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - plausible
    secrets:
      - plausible-conf

  crontab:
    build: ./crontab
    restart: always
    volumes:
      - ./backup:/backup
      - ./nginx-reverse-proxy/:/etc/nginx/
      - ./aws:/root/.aws
      - ./crontab/letsencrypt/conf:/etc/letsencrypt
      - ./crontab/letsencrypt/www:/var/www/certbot

    depends_on:
      - nginx
      - plausible_db
      - plausible_events_db
    secrets:
      - plausible-conf

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
  geoip:
    driver: local

secrets:
  plausible-conf:
    file: ./plausible-conf.env